# --- –°–∞–π—Ç ---
title: "üëæ –¶–∏—Ñ—Ä–æ–≤–æ–π —Å–∞–¥–∏–∫ üëæ"
description: "–ó–∞–º–µ—Ç–∫–∏, –º—ã—Å–ª–∏ –∏ –ø—Ä–æ–µ–∫—Ç—ã"
url: "https://dg.ada-dev.ru"   # —Ç–≤–æ–π –¥–æ–º–µ–Ω
baseurl: ""                    # –µ—Å–ª–∏ —Å–∞–π—Ç –≤ –∫–æ—Ä–Ω–µ –¥–æ–º–µ–Ω–∞
lang: ru-RU
favicon: /assets/images/favicons/favicon.ico

locale: ru

sass:
  style: compressed

analytics:
  provider: "google-gtag"   # –≤—Å—Ç—Ä–æ–µ–Ω–Ω–∞—è –∏–Ω—Ç–µ–≥—Ä–∞—Ü–∏—è
  google:
    tracking_id: "G-L27WKBFS0F"   # —Ç–≤–æ–π GA4 Measurement ID
    anonymize_ip: true            # –æ–ø—Ü–∏–æ–Ω–∞–ª—å–Ω–æ


# --- –¢–µ–º–∞ ---
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"  # –≤–∞—Ä–∏–∞–Ω—Ç—ã: default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise

breadcrumbs: true

# --- –ü–ª–∞–≥–∏–Ω—ã (—Å–æ–≤–º–µ—Å—Ç–∏–º—ã–µ —Å GitHub Pages) ---
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-obsidian


# --- –ü–∞–≥–∏–Ω–∞—Ü–∏—è –ø–æ—Å—Ç–æ–≤ (–µ—Å–ª–∏ –∏—Å–ø–æ–ª—å–∑—É–µ—à—å _posts) ---
# paginate: 10
# paginate_path: /page:num/

# --- –ö–æ–ª–ª–µ–∫—Ü–∏—è –∑–∞–º–µ—Ç–æ–∫ –¥–ª—è garden ---
collections:
  pages:
    output: true
    permalink: /:path/
  notes:
    output: true
    permalink: /notes/:title/

# --- –ó–Ω–∞—á–µ–Ω–∏—è –ø–æ —É–º–æ–ª—á–∞–Ω–∏—é (–ª–µ–π–∞—É—Ç—ã/–æ–ø—Ü–∏–∏) ---
defaults:
  - scope:
      path: ""
      type: "notes"
    values:
      layout: single
      sidebar:
        nav: ""
      toc: true          # –æ–≥–ª–∞–≤–ª–µ–Ω–∏–µ —Å–ø—Ä–∞–≤–∞
      toc_sticky: true
      author_profile: false
      show_date: true
      show_date_modified: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      sidebar:
        nav: ""
      toc: true          # –æ–≥–ª–∞–≤–ª–µ–Ω–∏–µ —Å–ø—Ä–∞–≤–∞
      toc_sticky: true
      author_profile: true
      show_date: true
      show_date_modified: falturse
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      sidebar:
        nav: ""
      toc: false          # –æ–≥–ª–∞–≤–ª–µ–Ω–∏–µ —Å–ø—Ä–∞–≤–∞
      toc_sticky: false
      author_profile: true
      show_date: true
      show_date_modified: true

obsidian:
  vault: "_notes"          # –≥–¥–µ –ª–µ–∂–∞—Ç md-—Ñ–∞–π–ª—ã Obsidian
  wikilinks: true          # –≤–∫–ª—é—á–∏—Ç—å [[wiki-—Å—Å—ã–ª–∫–∏]]
  # –Ω–∏–∂–µ ‚Äî —É–¥–æ–±–Ω—ã–µ –æ–ø—Ü–∏–∏
  downcase: true           # –ø—Ä–∏–≤–æ–¥–∏—Ç—å —Å—Å—ã–ª–∫–∏ –∫ –Ω–∏–∂–Ω–µ–º—É —Ä–µ–≥–∏—Å—Ç—Ä—É
  slugify: true            # –∑–∞–º–µ–Ω—è—Ç—å –ø—Ä–æ–±–µ–ª—ã/–∫–∏—Ä–∏–ª–ª–∏—Ü—É –Ω–∞ —Å–ª–∞–≥
  ext: ".md"
  attachments_dir: "assets/cache/"
  # graph: true

# --- –ù–∞–≤–∏–≥–∞—Ü–∏—è (–ø–æ–¥–∫–ª—é—á–∏–º _data/navigation.yml) ---
navigation:
  main: true

# --- –ü–æ–∏—Å–∫ (–≤—Å—Ç—Ä–æ–µ–Ω–Ω—ã–π lunr) ---
search: true

author:
  name: "–î–º–∏—Ç—Ä–∏–π –ê–Ω—Ç–∏–ø–µ–Ω–∫–æ"
  bio: "–ê—à–∞–ª–µ–ª—ã–π –ø—Ä–æ–ø–∞–≥–∞–Ω–¥–∏—Å—Ç –ª–∏–Ω—É–∫—Å–∞."
  avatar: /assets/images/avatar.png   # –æ–ø—Ü–∏–æ–Ω–∞–ª—å–Ω–æ
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ada-dmitry"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/moonlosk"
    - label: "–ö–∞–Ω–∞–ª"
      icon: "fab fa-telegram"
      url: "https://t.me/moonlosk–º—Ñ"
    - label: "VK"
      icon: "fab fa-vk"
      url: "https://vk.com/moonlosk"
    - label: "RSS"
      icon: "fas fa-rss"
      url: "/feed.xml"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ada-dmitry"
    - label: "Telegram"
      icon: "fab fa-telegram"
      url: "https://t.me/moonlosk"
    - label: "VK"
      icon: "fab fa-vk"
      url: "https://vk.com/moonlosk"
  since: "2025"


# --- –ü—Ä–æ—á–µ–µ ---
markdown: kramdown
permalink: /:categories/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _site

kramdown:
  input: GFM
  hard_wrap: true

